# Generated by Django 5.2.12 on 2026-04-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resources', '0001_initial'),
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='snapshots.snapshot'),
        ),
    ]
