# Generated by Django 5.2.12 on 2026-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('normalized_url', models.URLField(db_index=True, max_length=2000)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('title_manual', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('favorite', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('fetch_failed', 'Fetch Failed'), ('maybe_deleted', 'Maybe Deleted'), ('gone', 'Gone')], db_index=True, default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-favorite', '-updated_at', '-id'],
            },
        ),
    ]
