# Generated by Django 5.2.12 on 2026-04-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_link_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='last_link_check_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='last_link_check_http_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='link_status',
            field=models.CharField(choices=[('unchecked', '未確認'), ('active', '有効'), ('maybe_deleted', '要注意'), ('gone', 'リンク切れ'), ('error', '確認失敗')], db_index=True, default='unchecked', max_length=32),
        ),
        migrations.AddField(
            model_name='resource',
            name='review_state',
            field=models.CharField(choices=[('none', '未設定'), ('needs_review', '要確認'), ('done', '処理済み'), ('on_hold', '保留')], db_index=True, default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='resource',
            name='current_status',
            field=models.CharField(choices=[('active', '取得済み'), ('fetch_failed', '取得失敗'), ('maybe_deleted', '削除の可能性'), ('gone', '削除済み')], db_index=True, default='active', max_length=32),
        ),
    ]
