# Generated by Django 5.2.12 on 2026-04-02 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_no', models.PositiveIntegerField()),
                ('fetch_url', models.URLField(max_length=2000)),
                ('fetch_method', models.CharField(choices=[('http', 'HTTP'), ('playwright', 'Playwright')], default='http', max_length=32)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=500)),
                ('og_description', models.TextField(blank=True)),
                ('og_image_url', models.URLField(blank=True, max_length=2000)),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_category', models.CharField(blank=True, max_length=120)),
                ('ai_payload', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_html_path', models.CharField(blank=True, max_length=500)),
                ('raw_text_path', models.CharField(blank=True, max_length=500)),
                ('raw_json_path', models.CharField(blank=True, max_length=500)),
                ('screenshot_full_path', models.CharField(blank=True, max_length=500)),
                ('screenshot_taken_at', models.DateTimeField(blank=True, null=True)),
                ('page_height', models.PositiveIntegerField(blank=True, null=True)),
                ('viewport_width', models.PositiveIntegerField(blank=True, null=True)),
                ('viewport_height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_deleted_like', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='resources.resource')),
            ],
            options={
                'ordering': ['-fetched_at', '-id'],
                'unique_together': {('resource', 'snapshot_no')},
            },
        ),
    ]
