# Generated by Django 5.2.12 on 2026-04-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapshots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="image_assets",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
