# Generated by Django 5.2.12 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapshots", "0002_snapshot_image_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="video_assets",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
